
development:
  adapter: postgresql
  encoding: unicode
  database: appointment_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: appointment_test

  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: appointment_production

  pool: 5
  timeout: 5000
